import "server-only";

import { supabaseAdmin } from "../supabase-server";
import { ForgeAgentError, type ForgeAgentRun, type ForgeAgentRunStatus, type ForgeAgentStep, type ForgeAgentStepType, type ForgeAgentToolName, type ForgeRunArtifact, type ForgeRunArtifactInput } from "./agent-foundation";

type RunRow = { id: string; user_id: string; forge_project_id: string; conversation_id: string; workspace_id: string; runtime_id: string; status: ForgeAgentRunStatus; objective: string; base_commit_sha: string; plan: string[] | null; final_report: string | null; created_at: string; started_at: string | null; completed_at: string | null; last_activity_at: string | null; error: string | null };
type ArtifactRow = { id: string; run_id: string; repository: string; base_sha: string; source_branch: string; changed_files: string[]; additions: number; deletions: number; patch: string; status: "READY" | "EMPTY"; created_at: string };
type StepRow = { id: string; run_id: string; step_number: number; type: ForgeAgentStepType; summary: string; tool: ForgeAgentToolName | null; input: Record<string, unknown>; result_summary: string | null; status: "RUNNING" | "COMPLETED" | "FAILED"; started_at: string; completed_at: string | null };
const runFields = "id,user_id,forge_project_id,conversation_id,workspace_id,runtime_id,status,objective,base_commit_sha,plan,final_report,created_at,started_at,completed_at,last_activity_at,error";
const stepFields = "id,run_id,step_number,type,summary,tool,input,result_summary,status,started_at,completed_at";
const artifactFields = "id,run_id,repository,base_sha,source_branch,changed_files,additions,deletions,patch,status,created_at";
const encode = encodeURIComponent;
function mapRun(row: RunRow): ForgeAgentRun { return { runId: row.id, userId: row.user_id, projectId: row.forge_project_id, conversationId: row.conversation_id, workspaceId: row.workspace_id, runtimeId: row.runtime_id, status: row.status, objective: row.objective, baseCommitSha: row.base_commit_sha, plan: row.plan || [], finalReport: row.final_report, createdAt: row.created_at, startedAt: row.started_at, completedAt: row.completed_at, lastActivityAt: row.last_activity_at, error: row.error }; }
function mapArtifact(row: ArtifactRow): ForgeRunArtifact { return { artifactId: row.id, runId: row.run_id, repository: row.repository, baseCommitSha: row.base_sha, sourceBranch: row.source_branch, changedFiles: row.changed_files || [], additions: row.additions, deletions: row.deletions, patch: row.patch, status: row.status, createdAt: row.created_at }; }
function mapStep(row: StepRow): ForgeAgentStep { return { stepId: row.id, runId: row.run_id, stepNumber: row.step_number, type: row.type, summary: row.summary, tool: row.tool, input: row.input || {}, resultSummary: row.result_summary, status: row.status, startedAt: row.started_at, completedAt: row.completed_at }; }
function persistenceOperation(path: string, init: RequestInit) { const resource = path.includes("/forge_run_artifacts") ? "run_artifacts" : path.includes("/forge_agent_steps") ? "agent_steps" : path.includes("/forge_agent_runs") ? "agent_runs" : "agent_store"; return `${(init.method || "GET").toUpperCase()}_${resource}`; }
function safePersistenceCode(error: unknown) { const message = error instanceof Error ? error.message : ""; return message.match(/"code"\s*:\s*"([A-Z0-9_]+)"/i)?.[1]?.slice(0, 32) || "UNKNOWN"; }
async function request<T>(path: string, init: RequestInit = {}) { try { return await supabaseAdmin(path, init) as T; } catch (error) { const operation = persistenceOperation(path, init), code = safePersistenceCode(error); console.error("Forge agent persistence failure", { operation, code }); throw new ForgeAgentError("PERSISTENCE", `Persistance Forge impossible (${operation}, code ${code}).`); } }

export async function createAgentRun(input: Omit<ForgeAgentRun, "runId" | "createdAt">) { const active = await request<RunRow[]>(`/rest/v1/forge_agent_runs?user_id=eq.${encode(input.userId)}&runtime_id=eq.${encode(input.runtimeId)}&status=in.(QUEUED,PLANNING,RUNNING,VALIDATING)&select=${runFields}&limit=1`, { method: "GET" }); if (active[0]) throw new ForgeAgentError("CONFLICT", "Un run Forge est déjà actif pour ce runtime."); const body = { user_id: input.userId, forge_project_id: input.projectId, conversation_id: input.conversationId, workspace_id: input.workspaceId, runtime_id: input.runtimeId, status: input.status, objective: input.objective, base_commit_sha: input.baseCommitSha, plan: input.plan, final_report: input.finalReport, started_at: input.startedAt, completed_at: input.completedAt, last_activity_at: input.lastActivityAt, error: input.error }; const rows = await request<RunRow[]>(`/rest/v1/forge_agent_runs?select=${runFields}`, { method: "POST", body: JSON.stringify(body) }); if (!rows[0]) throw new ForgeAgentError("PERSISTENCE", "Le run Forge n’a pas pu être créé."); return mapRun(rows[0]); }
export async function updateAgentRun(userId: string, runId: string, input: Partial<Pick<ForgeAgentRun, "status" | "plan" | "finalReport" | "startedAt" | "completedAt" | "lastActivityAt" | "error">>) { const body = { ...(input.status !== undefined ? { status: input.status } : {}), ...(input.plan !== undefined ? { plan: input.plan } : {}), ...(input.finalReport !== undefined ? { final_report: input.finalReport } : {}), ...(input.startedAt !== undefined ? { started_at: input.startedAt } : {}), ...(input.completedAt !== undefined ? { completed_at: input.completedAt } : {}), ...(input.lastActivityAt !== undefined ? { last_activity_at: input.lastActivityAt } : {}), ...(input.error !== undefined ? { error: input.error } : {}) }; const rows = await request<RunRow[]>(`/rest/v1/forge_agent_runs?id=eq.${encode(runId)}&user_id=eq.${encode(userId)}&select=${runFields}`, { method: "PATCH", body: JSON.stringify(body) }); if (!rows[0]) throw new ForgeAgentError("NOT_FOUND", "Run Forge introuvable ou inaccessible."); return mapRun(rows[0]); }
export async function createAgentRunArtifact(userId: string, input: ForgeRunArtifactInput) { const run = await getAgentRun(userId, input.runId); if (!run) throw new ForgeAgentError("NOT_FOUND", "Run Forge introuvable ou inaccessible."); const body = { run_id: input.runId, user_id: userId, repository: input.repository, base_sha: input.baseCommitSha, source_branch: input.sourceBranch, changed_files: input.changedFiles, additions: input.additions, deletions: input.deletions, patch: input.patch, status: input.status }; const rows = await request<ArtifactRow[]>(`/rest/v1/forge_run_artifacts?select=${artifactFields}`, { method: "POST", body: JSON.stringify(body) }); if (!rows[0]) throw new ForgeAgentError("PERSISTENCE", "L’artifact Forge n’a pas pu être créé."); return mapArtifact(rows[0]); }
export async function getAgentRunArtifact(userId: string, runId: string) { const run = await getAgentRun(userId, runId); if (!run) throw new ForgeAgentError("NOT_FOUND", "Run Forge introuvable ou inaccessible."); const rows = await request<ArtifactRow[]>(`/rest/v1/forge_run_artifacts?run_id=eq.${encode(runId)}&user_id=eq.${encode(userId)}&select=${artifactFields}&limit=1`, { method: "GET" }); return rows[0] ? mapArtifact(rows[0]) : null; }
export async function insertAgentStep(userId: string, input: Omit<ForgeAgentStep, "stepId">) { const run = await getAgentRun(userId, input.runId); if (!run) throw new ForgeAgentError("NOT_FOUND", "Run Forge introuvable ou inaccessible."); const body = { run_id: input.runId, user_id: userId, step_number: input.stepNumber, type: input.type, summary: input.summary, tool: input.tool, input: input.input, result_summary: input.resultSummary, status: input.status, started_at: input.startedAt, completed_at: input.completedAt }; const rows = await request<StepRow[]>(`/rest/v1/forge_agent_steps?select=${stepFields}`, { method: "POST", body: JSON.stringify(body) }); if (!rows[0]) throw new ForgeAgentError("PERSISTENCE", "L’étape Forge n’a pas pu être enregistrée."); return mapStep(rows[0]); }
export async function updateAgentStep(userId: string, stepId: string, input: Pick<ForgeAgentStep, "resultSummary" | "status" | "completedAt">) { const body = { result_summary: input.resultSummary, status: input.status, completed_at: input.completedAt }; const rows = await request<StepRow[]>(`/rest/v1/forge_agent_steps?id=eq.${encode(stepId)}&user_id=eq.${encode(userId)}&select=${stepFields}`, { method: "PATCH", body: JSON.stringify(body) }); if (!rows[0]) throw new ForgeAgentError("NOT_FOUND", "Étape Forge introuvable ou inaccessible."); return mapStep(rows[0]); }
export async function getAgentRun(userId: string, runId: string) { const rows = await request<RunRow[]>(`/rest/v1/forge_agent_runs?id=eq.${encode(runId)}&user_id=eq.${encode(userId)}&select=${runFields}&limit=1`, { method: "GET" }); return rows[0] ? mapRun(rows[0]) : null; }
export async function getLatestAgentRun(userId: string, conversationId: string) { const rows = await request<RunRow[]>(`/rest/v1/forge_agent_runs?user_id=eq.${encode(userId)}&conversation_id=eq.${encode(conversationId)}&select=${runFields}&order=created_at.desc&limit=1`, { method: "GET" }); return rows[0] ? mapRun(rows[0]) : null; }
export async function listAgentRuns(userId: string, conversationId: string) { const rows = await request<RunRow[]>(`/rest/v1/forge_agent_runs?user_id=eq.${encode(userId)}&conversation_id=eq.${encode(conversationId)}&select=${runFields}&order=created_at.asc`, { method: "GET" }); return rows.map(mapRun); }
export async function listAgentSteps(userId: string, runId: string) { const run = await getAgentRun(userId, runId); if (!run) throw new ForgeAgentError("NOT_FOUND", "Run Forge introuvable ou inaccessible."); const rows = await request<StepRow[]>(`/rest/v1/forge_agent_steps?run_id=eq.${encode(runId)}&select=${stepFields}&order=step_number.asc`, { method: "GET" }); return rows.map(mapStep); }
export async function isAgentRunCancelled(userId: string, runId: string) { return (await getAgentRun(userId, runId))?.status === "CANCELLED"; }
export async function cancelAgentRun(userId: string, runId: string) { const run = await getAgentRun(userId, runId); if (!run) throw new ForgeAgentError("NOT_FOUND", "Run Forge introuvable ou inaccessible."); if (["COMPLETED", "FAILED", "CANCELLED"].includes(run.status)) return run; return updateAgentRun(userId, runId, { status: "CANCELLED", completedAt: new Date().toISOString(), lastActivityAt: new Date().toISOString() }); }
