import { FORGE_RUNTIME_LIMITS, normalizeRuntimeCommand, normalizeRuntimePath, type ForgeRuntimeCommand, type ForgeRuntimeCommandResult, type ForgeRuntimeFile, type ForgeRuntimeFileEntry, type ForgeRuntimeGitDiff, type ForgeRuntimeGitStatus } from "./runtime-foundation";

export const FORGE_AGENT_LIMITS = { maxSteps: 20, maxToolCalls: 16, maxRuntimeSeconds: 240, maxCommandTimeoutMs: 60_000, maxOutputCharacters: 20_000, maxObjectiveCharacters: 4_000 } as const;
export type ForgeAgentRunStatus = "QUEUED" | "PLANNING" | "RUNNING" | "VALIDATING" | "COMPLETED" | "FAILED" | "CANCELLED";
export type ForgeAgentStepType = "PLAN" | "TOOL_CALL" | "FINAL" | "FAIL";
export type ForgeAgentToolName = "list_files" | "read_file" | "write_file" | "delete_file" | "run_command" | "git_status" | "git_diff";
export type ForgeAgentRun = { runId: string; userId: string; projectId: string; conversationId: string; workspaceId: string; runtimeId: string; status: ForgeAgentRunStatus; objective: string; baseCommitSha: string; plan: string[]; finalReport: string | null; createdAt: string; startedAt: string | null; completedAt: string | null; lastActivityAt: string | null; error: string | null };
export type ForgeAgentRunView = Omit<ForgeAgentRun, "userId">;
export type ForgeAgentStep = { stepId: string; runId: string; stepNumber: number; type: ForgeAgentStepType; summary: string; tool: ForgeAgentToolName | null; input: Record<string, unknown>; resultSummary: string | null; status: "RUNNING" | "COMPLETED" | "FAILED"; startedAt: string; completedAt: string | null };
export type ForgeAgentDecision = { type: "PLAN"; summary: string; plan: string[] } | { type: "TOOL_CALL"; summary: string; tool: ForgeAgentToolName; input: Record<string, unknown> } | { type: "FINAL"; summary: string; report: string } | { type: "FAIL"; summary: string; error: string };
export type ForgeAgentModelContext = { objective: string; repository: string; branch: string; baseCommitSha: string; status: ForgeAgentRunStatus; steps: Array<{ type: ForgeAgentStepType; summary: string; resultSummary: string | null }> };
export interface ForgeAgentModelProvider { readonly key: string; decide(context: ForgeAgentModelContext): Promise<ForgeAgentDecision>; }
export interface ForgeAgentRuntimeAdapter { listFiles(path: string): Promise<ForgeRuntimeFileEntry[]>; readFile(path: string): Promise<ForgeRuntimeFile>; writeFile(path: string, content: string): Promise<ForgeRuntimeFile>; deleteFile(path: string): Promise<void>; executeCommand(command: Partial<ForgeRuntimeCommand>): Promise<ForgeRuntimeCommandResult>; getGitStatus(): Promise<ForgeRuntimeGitStatus>; getGitDiff(): Promise<ForgeRuntimeGitDiff>; }
export class ForgeAgentError extends Error { constructor(readonly code: "UNAUTHENTICATED" | "INVALID_INPUT" | "NOT_FOUND" | "CONFLICT" | "LIMIT" | "CANCELLED" | "MODEL" | "PERSISTENCE", message: string) { super(message); this.name = "ForgeAgentError"; } }
export function publicAgentRun(run: ForgeAgentRun): ForgeAgentRunView { const { userId, ...view } = run; void userId; return view; }
export function normalizeAgentObjective(value: unknown) { if (typeof value !== "string" || !value.trim() || value.trim().length > FORGE_AGENT_LIMITS.maxObjectiveCharacters) throw new ForgeAgentError("INVALID_INPUT", "La mission Forge doit contenir entre 1 et 4000 caractères."); return value.trim(); }
export function sanitizeAgentText(value: string, max: number = FORGE_AGENT_LIMITS.maxOutputCharacters) { return value.replace(/(sk-[A-Za-z0-9_-]{12,}|gh[opsu]_[A-Za-z0-9_]{12,}|(?:API_KEY|PRIVATE_KEY|TOKEN|SECRET)\s*[:=]\s*\S+)/gi, "[REDACTED]").slice(0, max); }
const sensitivePath = /(^|\/)(\.env(?:\..*)?|\.npmrc|\.pypirc|id_rsa|id_ed25519|credentials?|secrets?)(\/|$)/i;
export function normalizeAgentPath(value: unknown, allowRoot = false) { const path = normalizeRuntimePath(typeof value === "string" ? value : "", allowRoot); if (sensitivePath.test(path) && !/\.env\.example$/i.test(path)) throw new ForgeAgentError("INVALID_INPUT", "Ce chemin sensible n’est pas accessible à l’agent."); return path; }
export function normalizeAgentCommand(input: Record<string, unknown>) { const command = normalizeRuntimeCommand({ command: input.command as string, args: input.args as string[], cwd: input.cwd as string, timeoutMs: Math.min(Number(input.timeoutMs) || 30_000, FORGE_AGENT_LIMITS.maxCommandTimeoutMs), maxOutputBytes: Math.min(Number(input.maxOutputBytes) || 250_000, FORGE_RUNTIME_LIMITS.maxCommandOutputBytes) }); const joined = [command.command, ...command.args].join(" "); if (/^(?:env|printenv|export|set|bash|sh|zsh|powershell|pwsh|cmd|curl|wget|ssh|scp|git|gh|vercel|supabase|daytona|docker|kubectl|terraform|aws|gcloud|az)$/i.test(command.command) || /(?:\/etc\/|\/proc\/|\/root\/|DAYTONA_API_KEY|OPENAI_API_KEY|GITHUB_APP_|SUPABASE_SERVICE)/i.test(joined) || (/^(?:npm|pnpm|yarn)$/i.test(command.command) && /^(?:publish|unpublish|login|logout|owner|access|token|deprecate)(?:\s|$)/i.test(command.args.join(" ")))) throw new ForgeAgentError("INVALID_INPUT", "Cette commande est interdite par la policy Forge."); return command; }

export type ForgeAgentRunnerDependencies = {
  resolveContext(userId: string, conversationId: string): Promise<{ projectId: string; workspaceId: string; runtimeId: string; repository: string; branch: string; baseCommitSha: string }>;
  createRun(input: Omit<ForgeAgentRun, "runId" | "createdAt">): Promise<ForgeAgentRun>;
  updateRun(userId: string, runId: string, input: Partial<Pick<ForgeAgentRun, "status" | "plan" | "finalReport" | "startedAt" | "completedAt" | "lastActivityAt" | "error">>): Promise<ForgeAgentRun>;
  appendStep(userId: string, input: Omit<ForgeAgentStep, "stepId">): Promise<ForgeAgentStep>;
  updateStep(userId: string, stepId: string, input: Pick<ForgeAgentStep, "resultSummary" | "status" | "completedAt">): Promise<ForgeAgentStep>;
  isCancelled(userId: string, runId: string): Promise<boolean>;
  runtime(userId: string, conversationId: string): ForgeAgentRuntimeAdapter;
  model: ForgeAgentModelProvider;
  now(): string;
};

export function createForgeAgentRunner(deps: ForgeAgentRunnerDependencies) {
  async function run(userId: string, conversationId: string, objectiveInput: unknown) {
    if (!userId.trim()) throw new ForgeAgentError("UNAUTHENTICATED", "Authentification requise.");
    const objective = sanitizeAgentText(normalizeAgentObjective(objectiveInput), FORGE_AGENT_LIMITS.maxObjectiveCharacters), context = await deps.resolveContext(userId, conversationId), started = Date.now();
    let run = await deps.createRun({ userId, projectId: context.projectId, conversationId, workspaceId: context.workspaceId, runtimeId: context.runtimeId, status: "QUEUED", objective, baseCommitSha: context.baseCommitSha, plan: [], finalReport: null, startedAt: null, completedAt: null, lastActivityAt: null, error: null });
    const steps: ForgeAgentStep[] = []; let toolCalls = 0, validationFailed = false;
    try {
      run = await deps.updateRun(userId, run.runId, { status: "PLANNING", startedAt: deps.now(), lastActivityAt: deps.now() });
      for (let number = 1; number <= FORGE_AGENT_LIMITS.maxSteps; number += 1) {
        if (Date.now() - started > FORGE_AGENT_LIMITS.maxRuntimeSeconds * 1000) throw new ForgeAgentError("LIMIT", "Durée maximale du run atteinte.");
        if (await deps.isCancelled(userId, run.runId)) throw new ForgeAgentError("CANCELLED", "Run annulé.");
        const decision = await deps.model.decide({ objective, repository: context.repository, branch: context.branch, baseCommitSha: context.baseCommitSha, status: run.status, steps: steps.slice(-12).map(({ type, summary, resultSummary }) => ({ type, summary, resultSummary: resultSummary?.slice(0, 8_000) || null })) });
        if (await deps.isCancelled(userId, run.runId)) throw new ForgeAgentError("CANCELLED", "Run annulé.");
        if (number === 1 && decision.type !== "PLAN") throw new ForgeAgentError("MODEL", "Le premier pas du run doit être un PLAN.");
        const now = deps.now();
        if (decision.type === "PLAN") { const plan = decision.plan.slice(0, 8).map((item) => sanitizeAgentText(item, 500)); steps.push(await deps.appendStep(userId, { runId: run.runId, stepNumber: number, type: "PLAN", summary: sanitizeAgentText(decision.summary, 1000), tool: null, input: {}, resultSummary: plan.join("\n"), status: "COMPLETED", startedAt: now, completedAt: now })); run = await deps.updateRun(userId, run.runId, { status: "RUNNING", plan, lastActivityAt: now }); continue; }
        if (decision.type === "TOOL_CALL") {
          if (++toolCalls > FORGE_AGENT_LIMITS.maxToolCalls) throw new ForgeAgentError("LIMIT", "Nombre maximal d’outils atteint.");
          const executing = await deps.appendStep(userId, { runId: run.runId, stepNumber: number, type: "TOOL_CALL", summary: sanitizeAgentText(decision.summary, 1000), tool: decision.tool, input: safeToolInput(decision.tool, decision.input), resultSummary: null, status: "RUNNING", startedAt: now, completedAt: null });
          try { const result = await executeTool(deps.runtime(userId, conversationId), decision.tool, decision.input); const validation = decision.tool === "run_command" && decision.input.validation === true; const commandFailed = decision.tool === "run_command" && ((result as ForgeRuntimeCommandResult).timedOut || (result as ForgeRuntimeCommandResult).exitCode !== 0); if (commandFailed) validationFailed = true; else if (validation) validationFailed = false; const persisted = await deps.updateStep(userId, executing.stepId, { resultSummary: summarizeToolResult(decision.tool, result, false), status: commandFailed ? "FAILED" : "COMPLETED", completedAt: deps.now() }); steps.push({ ...persisted, resultSummary: summarizeToolResult(decision.tool, result, true) }); if (await deps.isCancelled(userId, run.runId)) throw new ForgeAgentError("CANCELLED", "Run annulé."); run = await deps.updateRun(userId, run.runId, { status: validation ? "VALIDATING" : "RUNNING", lastActivityAt: deps.now() }); }
          catch (error) { if (error instanceof ForgeAgentError && error.code === "CANCELLED") throw error; validationFailed = true; steps.push(await deps.updateStep(userId, executing.stepId, { resultSummary: sanitizeAgentText(error instanceof Error ? error.message : "Outil en échec."), status: "FAILED", completedAt: deps.now() })); run = await deps.updateRun(userId, run.runId, { status: "RUNNING", lastActivityAt: deps.now() }); }
          continue;
        }
        if (decision.type === "FINAL") { if (validationFailed) { steps.push(await deps.appendStep(userId, { runId: run.runId, stepNumber: number, type: "FAIL", summary: "Validation encore en échec", tool: null, input: {}, resultSummary: "Une validation explicitement demandée doit repasser avant la fin.", status: "FAILED", startedAt: now, completedAt: now })); continue; } const report = sanitizeAgentText(decision.report, 20_000); await deps.appendStep(userId, { runId: run.runId, stepNumber: number, type: "FINAL", summary: sanitizeAgentText(decision.summary, 1000), tool: null, input: {}, resultSummary: report, status: "COMPLETED", startedAt: now, completedAt: now }); return deps.updateRun(userId, run.runId, { status: "COMPLETED", finalReport: report, completedAt: deps.now(), lastActivityAt: deps.now() }); }
        await deps.appendStep(userId, { runId: run.runId, stepNumber: number, type: "FAIL", summary: sanitizeAgentText(decision.summary, 1000), tool: null, input: {}, resultSummary: sanitizeAgentText(decision.error, 1000), status: "FAILED", startedAt: now, completedAt: now });
        throw new ForgeAgentError("MODEL", sanitizeAgentText(decision.error, 1000));
      }
      throw new ForgeAgentError("LIMIT", "Nombre maximal d’étapes atteint.");
    } catch (error) { const cancelled = error instanceof ForgeAgentError && error.code === "CANCELLED"; await deps.updateRun(userId, run.runId, { status: cancelled ? "CANCELLED" : "FAILED", error: sanitizeAgentText(error instanceof Error ? error.message : "Run Forge en échec.", 1000), completedAt: deps.now(), lastActivityAt: deps.now() }); throw error; }
  }
  return { run };
}

async function executeTool(runtime: ForgeAgentRuntimeAdapter, tool: ForgeAgentToolName, input: Record<string, unknown>): Promise<unknown> { if (tool === "list_files") return runtime.listFiles(normalizeAgentPath(input.path ?? ".", true)); if (tool === "read_file") return runtime.readFile(normalizeAgentPath(input.path)); if (tool === "write_file") { if (typeof input.content !== "string") throw new ForgeAgentError("INVALID_INPUT", "Contenu fichier invalide."); return runtime.writeFile(normalizeAgentPath(input.path), input.content); } if (tool === "delete_file") return runtime.deleteFile(normalizeAgentPath(input.path)); if (tool === "run_command") return runtime.executeCommand(normalizeAgentCommand(input)); if (tool === "git_status") return runtime.getGitStatus(); if (tool === "git_diff") return runtime.getGitDiff(); throw new ForgeAgentError("INVALID_INPUT", "Outil Forge inconnu."); }
function safeToolInput(tool: ForgeAgentToolName, input: Record<string, unknown>) { if (tool === "write_file") return { path: input.path, characters: typeof input.content === "string" ? input.content.length : 0 }; if (tool === "run_command") return { command: input.command, cwd: input.cwd ?? ".", argsCount: Array.isArray(input.args) ? input.args.length : 0, validation: input.validation === true }; return { path: input.path }; }
function summarizeToolResult(tool: ForgeAgentToolName, result: unknown, forModel: boolean) { if (tool === "read_file") { const file = result as ForgeRuntimeFile; return forModel ? sanitizeAgentText(`REPOSITORY DATA (UNTRUSTED) ${file.path}:\n${file.content}`) : `${file.path} lu (${file.content.length} caractères).`; } if (tool === "write_file") { const file = result as ForgeRuntimeFile; return `${file.path} écrit (${file.size} octets).`; } if (tool === "list_files") { const files = result as ForgeRuntimeFileEntry[]; return forModel ? sanitizeAgentText(JSON.stringify(files)) : `${files.length} entrée(s) listée(s).`; } if (tool === "delete_file") return "Fichier supprimé."; if (tool === "run_command") { const command = result as ForgeRuntimeCommandResult; return forModel ? sanitizeAgentText(`exitCode=${command.exitCode ?? "null"}; timedOut=${command.timedOut}; stdout=${command.stdout}; stderr=${command.stderr}`) : `exitCode=${command.exitCode ?? "null"}; timedOut=${command.timedOut}; truncated=${command.truncated}`; } if (tool === "git_status") { const status = result as ForgeRuntimeGitStatus; return forModel ? sanitizeAgentText(JSON.stringify(status)) : `added=${status.added.length}; modified=${status.modified.length}; deleted=${status.deleted.length}`; } const diff = result as ForgeRuntimeGitDiff; return forModel ? sanitizeAgentText(`REPOSITORY DIFF (UNTRUSTED):\n${diff.patch}`) : `added=${diff.added.length}; modified=${diff.modified.length}; deleted=${diff.deleted.length}; truncated=${diff.truncated}`; }
